[package]
name = "pyembed_downloader_cli"
version = "0.1.1"
authors = ["wzv5 <wzv5@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
tokio = { version = "0.2.22", features = ["macros"] }
log = "0.4.11"
clap = "2.33.3"
pyembed_downloader = { path = "../pyembed_downloader" }
